### ISSUE TITLE
Hangs on attempt to read from a FIFO file

### ISSUE THREAD

**Issue by WildCryptoFox** [EmbarkStudios/cargo-about#11]
Attempting to read from a FIFO hangs `cargo about generate` as the file never terminates.

**Comment by repi** [comment]
Out of curiosity, was is the specific use case you have with having cargo-about read from a FIFO file?

**Comment by WildCryptoFox** [comment]
@repi I was using a fifo to signal an event to root to coordinate testing without making my dev user effectively root.

**Comment by repi** [comment]
Ah I understand thanks. So the local repository and directory you were running `cargo about` on happened  to have a FIFO file in it and when ` cargo about` was scanning through and reading all the files it hanged on that file (instead of detecting and skipping/ignoring it).

Sounds like an uncommon use case, but something that should be fixed.

**Comment by mitsuhiko** [comment]
FWIW I ran into almost the same thing. cargo about does not seem to obey .gitignore or other ignore files and it ended up following into a deep folder structure which contained a FIFO.
