### ISSUE TITLE
[Question] license check on ring issue

### ISSUE THREAD

**Issue by Geobert** [EmbarkStudios/cargo-about#193]
I think I'm missing something but when running `cargo about generate about.hbs`, I bump into this error:
```
error: failed to satisfy license requirements
   ┌─ /home/geobert/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.20/Cargo.toml:28:13
   │
28 │ license = "(GPL-1.0-or-later AND OpenSSL AND OpenSSL OR (BSD-3-Clause OR GPL-1.0-or-later)) AND (ISC) AND (ISC AND MIT AND NOASSERTION AND OpenSSL) AND (MIT) AND (NOASSERTION) AND (NOASSERTION AND OpenSSL) AND (OpenSSL) AND (OpenSSL AND OpenSSL OR (BSD-3-Clause OR (GPL-1.0-or-later OR GPL-2.0-only))) AND (OpenSSL AND OpenSSL OR (BSD-3-Clause OR GPL-1.0-or-later))"
```

I tried to put in `about.toml`:
```
[ring]
accepted = ["OpenSSL"]

[ring.clarify]
license = "ISC AND MIT AND OpenSSL"
```

with no luck.

What am I doing wrong?

Thanks!

**Comment by Jake-Shadle** [comment]
You have not specified https://embarkstudios.github.io/cargo-about/cli/generate/config.html#the-files-andor-git-field which is required. I'll make a separate issue that that should be an error if you don't specify it.

I would recommend using https://embarkstudios.github.io/cargo-about/cli/generate/config.html#the-workarounds-field-optional since `ring` can be clarified there.

**Comment by Geobert** [comment]
Oh I see, I was sure I was missing something here! Thanks!
