### ISSUE TITLE
unicode-ident no longer getting its Unicode License Agreement from the crate [regression from 0.6.2]

### ISSUE THREAD

**Issue by jrose-signal** [EmbarkStudios/cargo-about#267]
With cargo-about 0.6.2, a crate depending on [unicode-ident](https://github.com/dtolnay/unicode-ident) 1.0.13 would (correctly) get two licenses listed, per its license of `(MIT OR Apache-2.0) AND Unicode-DFS-2016`. Both of these were pulled from the source files of the crate. With cargo-about 0.6.5, both licenses still appear, but the Unicode license is now "synthesized".

I don't have a standalone repro, but I doubt it's anything strange we're doing; still, here are the steps for us:

1. Check out https://github.com/signalapp/libsignal/releases/tag/v0.62.0, whose acknowledgments were generated by cargo-about 0.6.2.
2. Install cargo-about 0.6.5
3. Change acknowledgments/cargo-about-version to 0.6.5
4. Run bin/regenerate-acknowledgments.sh
5. Observe the diff in acknowledgments/acknowledgments.html

(Note that the license file for `ryu` is also newly marked synthesized, but is not actually synthesized; this is because the crate really does contain a license template without the name filled in. I'm not sure why this behavior would have changed between 0.6.2 and 0.6.5, though, so maybe it's related. `half` has a similar problem even in 0.6.2.)

**Comment by Jake-Shadle** [comment]
The issue seems to be that the [license text](https://github.com/dtolnay/unicode-ident/blob/master/LICENSE-UNICODE) differs significantly enough from the [canonical text](https://spdx.org/licenses/Unicode-DFS-2016.html) that it actually ends up being a closer match to [Unicode-3.0](https://spdx.org/licenses/Unicode-3.0.html), and since that license isn't used by the crate it falls back to the canonical text the crate says it is licensed under.

As far as why the behavior differs, I forgot to update the spdx cache used by askalono, so it was using the 3.18.0 license list data, which didn't have the Unicode-3.0 license at all, so the Unicode-DFS-2016 text would be the closest match.

I'll add a workaround since this crate is used everywhere, but open a PR to use the actual correct text.
